# Copyright (c) Facebook, Inc. and its affiliates. All rights reserved.
#screen -dmS "if" bash -c 'bash preprocess/save_zip.sh shiba-haru-1001'
#screen -dmS "if" bash -c 'bash preprocess/save_zip.sh shiba-haru-1002'
#screen -dmS "if" bash -c 'bash preprocess/save_zip.sh shiba-haru-1003'
#screen -dmS "if" bash -c 'bash preprocess/save_zip.sh shiba-haru-1004'
#screen -dmS "if" bash -c 'bash preprocess/save_zip.sh shiba-haru-1005'
#screen -dmS "if" bash -c 'bash preprocess/save_zip.sh shiba-haru-1006'
#screen -dmS "if" bash -c 'bash preprocess/save_zip.sh shiba-haru-1007'
#screen -dmS "if" bash -c 'bash preprocess/save_zip.sh shiba-haru-1008'
#screen -dmS "if" bash -c 'bash preprocess/save_zip.sh shiba-haru-1009'
#screen -dmS "if" bash -c 'bash preprocess/save_zip.sh shiba-haru-1010'
#screen -dmS "if" bash -c 'bash preprocess/save_zip.sh shiba-haru-1011'
#screen -dmS "if" bash -c 'bash preprocess/save_zip.sh shiba-haru-1012'
#screen -dmS "if" bash -c 'bash preprocess/save_zip.sh shiba-haru-1013'

#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 0 shiba-haru-1 logdir/shiba-haru-1-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "0"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 1 shiba-haru-1 logdir/shiba-haru-1-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "1"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 2 shiba-haru-1 logdir/shiba-haru-1-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "2"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 3 shiba-haru-1 logdir/shiba-haru-1-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "3"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 4 shiba-haru-1 logdir/shiba-haru-1-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "4"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 5 shiba-haru-1 logdir/shiba-haru-1-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "5"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 6 shiba-haru-1 logdir/shiba-haru-1-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "6"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 7 shiba-haru-1 logdir/shiba-haru-1-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "7"'
#sleep 300
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 0 shiba-haru-1 logdir/shiba-haru-1-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "8"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 1 shiba-haru-1 logdir/shiba-haru-1-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "9"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 2 shiba-haru-1 logdir/shiba-haru-1-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "10"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 3 shiba-haru-1 logdir/shiba-haru-1-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "11"'

#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 0 cat-socks logdir/cat-socks-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "0"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 1 cat-socks logdir/cat-socks-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "1"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 2 cat-socks logdir/cat-socks-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "2"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 3 cat-socks logdir/cat-socks-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "3"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 4 cat-socks logdir/cat-socks-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "4"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 5 cat-socks logdir/cat-socks-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "5"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 6 cat-socks logdir/cat-socks-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "6"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 7 cat-socks logdir/cat-socks-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "7"'

screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 0 cat-pikachiu logdir/cat-pikachiu-lbs-rkopt-120-b256-sph-init/params_latest.pth "0"'
screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 1 cat-pikachiu logdir/cat-pikachiu-lbs-rkopt-120-b256-sph-init/params_latest.pth "1"'
screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 2 cat-pikachiu logdir/cat-pikachiu-lbs-rkopt-120-b256-sph-init/params_latest.pth "2"'
screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 3 cat-pikachiu logdir/cat-pikachiu-lbs-rkopt-120-b256-sph-init/params_latest.pth "3"'
screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 4 cat-pikachiu logdir/cat-pikachiu-lbs-rkopt-120-b256-sph-init/params_latest.pth "4"'
screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 5 cat-pikachiu logdir/cat-pikachiu-lbs-rkopt-120-b256-sph-init/params_latest.pth "5"'
screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 6 cat-pikachiu logdir/cat-pikachiu-lbs-rkopt-120-b256-sph-init/params_latest.pth "6"'
screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 7 cat-pikachiu logdir/cat-pikachiu-lbs-rkopt-120-b256-sph-init/params_latest.pth "7"'
sleep 300
screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 0 cat-pikachiu logdir/cat-pikachiu-lbs-rkopt-120-b256-sph-init/params_latest.pth "8"'
screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 1 cat-pikachiu logdir/cat-pikachiu-lbs-rkopt-120-b256-sph-init/params_latest.pth "9"'
screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 2 cat-pikachiu logdir/cat-pikachiu-lbs-rkopt-120-b256-sph-init/params_latest.pth "10"'
sleep 300

#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 0 adult7 logdir/adult7-lbs-rkopt-120-b256-noellips-init/params_latest.pth "0"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 1 adult7 logdir/adult7-lbs-rkopt-120-b256-noellips-init/params_latest.pth "1"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 2 adult7 logdir/adult7-lbs-rkopt-120-b256-noellips-init/params_latest.pth "2"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 3 adult7 logdir/adult7-lbs-rkopt-120-b256-noellips-init/params_latest.pth "3"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 4 adult7 logdir/adult7-lbs-rkopt-120-b256-noellips-init/params_latest.pth "4"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 5 adult7 logdir/adult7-lbs-rkopt-120-b256-noellips-init/params_latest.pth "5"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 6 adult7 logdir/adult7-lbs-rkopt-120-b256-noellips-init/params_latest.pth "6"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 7 adult7 logdir/adult7-lbs-rkopt-120-b256-noellips-init/params_latest.pth "7"'
#sleep 600
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 0 adult7 logdir/adult7-lbs-rkopt-120-b256-noellips-init/params_latest.pth "8"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 1 adult7 logdir/adult7-lbs-rkopt-120-b256-noellips-init/params_latest.pth "9"'

#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 1 cat-coco logdir/cat-coco-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "0"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 2 cat-coco logdir/cat-coco-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "1"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 3 cat-coco logdir/cat-coco-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "2"'
#sleep 600
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 1 cat-coco logdir/cat-coco-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "3"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 2 cat-coco logdir/cat-coco-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "4"'
#screen -dmS "if" bash -c 'bash scripts/render_mgpu.sh 3 cat-coco logdir/cat-coco-lbs-rkopt-120-b64-fn-fix-init/params_latest.pth "5"'
